language: c

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y mpi-default-bin mpi-default-dev
  - sudo apt-get install python3

compiler:
  - gcc

install:
  - pip install pytest --user

script:
  - make units-check
  - make check
  - python3 -m pytest .

