language: python
python:
  - "3.6.7"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y mpi-default-bin mpi-default-dev
  - sudo apt-get install -y libomp-dev

compiler:
  - gcc

install:
  - pip install -r requirements.txt

script:
  - make units-check
  - make check
  - make
  - python3 -m pytest .
  - make -B WITH_OMP=2 check 
  - make -B WITH_MPI=2 check
  - make -B WITH_MPI=2 WITH_OMP=2 check
