language: python
python:
  - "3.6.7"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libomp-dev
  - pushd scripts
  - sudo ./get_mpich.sh
  - popd

compiler:
  - gcc

install:
  - pip install -r requirements.txt

script:
  - make units-check
  - make check
  - make check WITH_MPI=2
  - make check WITH_OMP=2
  - make check WITH_OMP=1 WITH_MPI=2
  - make check WITH_OMP=2 WITH_MPI=1
  - python3 -m pytest .
